### ISSUE TITLE
New User Image/Text

### ISSUE THREAD

**Issue by PnsDev** [hellbound1337/discord-revamp#2]
http://share.pnsdev.com/uploads/hfzpujys.png
^ misplaced

**Comment by PnsDev** [comment]
Same for hover tool-tip in calls
http://share.pnsdev.com/uploads/0b1k49jc.png

**Comment by hellbound1337** [comment]
Both discord issues, however if you change the zoom in values to this 
https://media.wtf/49637949
your tooltip issues should be fixed.

The profile one is discords fault.
